# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be12a8f976f37b087d1a81e469aeee913061a58edebb6d54ba0c2e24ba641fec8a9f9e8c30196912df1e09505c3adf963b29a75567d02f742558cb43c635b430

test:
  secret_key_base: f22a07e85f703f495abe7f2f8ccd06464f662bc4b8f49540e51037eeea29e8fc296ff5e02f2b40857c5c2b443f5ae7426b7ebf8264e3ab90db91d3b4a192491b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
